/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "ERC165Support",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165Support__factory>;
    getContractFactory(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721__factory>;
    getContractFactory(
      name: "ERC721Basic",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721Basic__factory>;
    getContractFactory(
      name: "ERC721BasicToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721BasicToken__factory>;
    getContractFactory(
      name: "ERC721Enumerable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721Enumerable__factory>;
    getContractFactory(
      name: "ERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721Metadata__factory>;
    getContractFactory(
      name: "ERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721Receiver__factory>;
    getContractFactory(
      name: "ERC721Token",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721Token__factory>;
    getContractFactory(
      name: "EstateRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EstateRegistry__factory>;
    getContractFactory(
      name: "EstateStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EstateStorage__factory>;
    getContractFactory(
      name: "IEstateRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IEstateRegistry__factory>;
    getContractFactory(
      name: "IMiniMeToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMiniMeToken__factory>;
    getContractFactory(
      name: "LANDRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LANDRegistry__factory>;
    getContractFactory(
      name: "Migratable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Migratable__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;

    getContractAt(
      name: "ERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "ERC165Support",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165Support>;
    getContractAt(
      name: "ERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721>;
    getContractAt(
      name: "ERC721Basic",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721Basic>;
    getContractAt(
      name: "ERC721BasicToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721BasicToken>;
    getContractAt(
      name: "ERC721Enumerable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721Enumerable>;
    getContractAt(
      name: "ERC721Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721Metadata>;
    getContractAt(
      name: "ERC721Receiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721Receiver>;
    getContractAt(
      name: "ERC721Token",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721Token>;
    getContractAt(
      name: "EstateRegistry",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EstateRegistry>;
    getContractAt(
      name: "EstateStorage",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EstateStorage>;
    getContractAt(
      name: "IEstateRegistry",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IEstateRegistry>;
    getContractAt(
      name: "IMiniMeToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMiniMeToken>;
    getContractAt(
      name: "LANDRegistry",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LANDRegistry>;
    getContractAt(
      name: "Migratable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Migratable>;
    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
