/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface LANDStorageInterface extends ethers.utils.Interface {
  functions: {
    "updateManager(address,address)": FunctionFragment;
    "latestPing(address)": FunctionFragment;
    "authorizedDeploy(address)": FunctionFragment;
    "registeredBalance(address)": FunctionFragment;
    "landBalance()": FunctionFragment;
    "updateOperator(uint256)": FunctionFragment;
    "estateRegistry()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "updateManager",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "latestPing", values: [string]): string;
  encodeFunctionData(
    functionFragment: "authorizedDeploy",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredBalance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "landBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateOperator",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "estateRegistry",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "updateManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "latestPing", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizedDeploy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "landBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estateRegistry",
    data: BytesLike
  ): Result;

  events: {};
}

export class LANDStorage extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: LANDStorageInterface;

  functions: {
    updateManager(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    latestPing(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    authorizedDeploy(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    registeredBalance(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    landBalance(overrides?: CallOverrides): Promise<[string]>;

    updateOperator(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    estateRegistry(overrides?: CallOverrides): Promise<[string]>;
  };

  updateManager(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  latestPing(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  authorizedDeploy(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  registeredBalance(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  landBalance(overrides?: CallOverrides): Promise<string>;

  updateOperator(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  estateRegistry(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    updateManager(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    latestPing(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    authorizedDeploy(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    registeredBalance(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    landBalance(overrides?: CallOverrides): Promise<string>;

    updateOperator(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    estateRegistry(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    updateManager(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    latestPing(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    authorizedDeploy(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registeredBalance(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    landBalance(overrides?: CallOverrides): Promise<BigNumber>;

    updateOperator(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    estateRegistry(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    updateManager(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    latestPing(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    authorizedDeploy(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registeredBalance(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    landBalance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updateOperator(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    estateRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
