/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  OwnableStorage,
  OwnableStorageInterface,
} from "../OwnableStorage";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "owner",
    outputs: [
      {
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

export class OwnableStorage__factory {
  static readonly abi = _abi;
  static createInterface(): OwnableStorageInterface {
    return new utils.Interface(_abi) as OwnableStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OwnableStorage {
    return new Contract(address, _abi, signerOrProvider) as OwnableStorage;
  }
}
